### ISSUE TITLE
Laravel 5.4 inconsistency

### ISSUE THREAD

**Issue by ghost** [sngrl/sphinxsearch#19]
Hello,
I had tried to install sngrl/sphinxsearch to Laravel 5.4 and I got these:
1) Providers array format is not the same with the one given in the project but you can adjust it to the proper format easily: Remove single quotes and ::class to the end of the class before the comma.  
2) Publishing config file gives error. Error message is below:
  [Symfony\Component\Debug\Exception\FatalThrowableError]              
  Call to undefined method Illuminate\Foundation\Application::share()  

Hope these will be solved.

**Comment by woodymendoza** [comment]
The issues is in:

vendor/sngrl/sphinxsearch/src/sngrl/SphinxSearch/SphinxSearchServiceProvider.php:10

replace: 

`$this->app['sphinxsearch'] = $this->app->share(function ($app) {`
       `return new SphinxSearch;`
`  });`

with: 

` $this->app->singleton(SphinxSearch::class, function ($app) {`
`return new SphinxSearch;`
`});`

Laravel 5.4 removed share and its now called singleton.   Pull request is below.
#20

**Comment by HugBoomsj** [comment]
i want , publish the configuration into my app. 
php artisan vendor:publish --provider=sngrl\SphinxSearch\SphinxSearchServiceProvider --force
but error notice

 [Symfony\Component\Debug\Exception\FatalErrorException]              
  Call to undefined method Illuminate\Foundation\Application::share()

**Comment by sngrl** [comment]
Fixed
