### ISSUE TITLE
PHP artisan vendor publish issue

### ISSUE THREAD

**Issue by noprobz09** [sngrl/sphinxsearch#2]
Hi,

I tried to install this package but I got problem when try to run "php artisan vendor:publish sngrl/sphinxsearch", it says "Too many arguments", Im using Laravel 5.0

Thank you,
Noel

**Comment by sngrl** [comment]
Good day!

In Laravel 5 you must use this command:
`php artisan vendor:publish --provider=sngrl\SphinxSearch\SphinxSearchServiceProvider --force`

I fix readme, thank you.

**Comment by noprobz09** [comment]
Hello sngrl,

Good day! :)

I tried again but it says, "Nothing to publish".
Screenshot: http://screencast.com/t/R3UguHsxjo4B

Thank you,
Noel

**Comment by noprobz09** [comment]
I think its working now by using <code>php artisan vendor:publish</code> :)

**Comment by DinicChen** [comment]
How did you deal with the problem？

**Comment by DinicChen** [comment]
ok, i resolve it...
