### ISSUE TITLE
Using share()

### ISSUE THREAD

**Issue by JeremyHutchings** [sngrl/sphinxsearch#26]
> php artisan vendor:publish --provider=sngrl\SphinxSearch\SphinxSearchServiceProvider --force

Results in : 

```
[Symfony\Component\Debug\Exception\FatalThrowableError]              
Call to undefined method Illuminate\Foundation\Application::share()  
```
As of laravel 5.4 share has been removed. You will have to use the singleton instead.

See: https://github.com/laravel/framework/commit/1a1969b6e6f793c3b2a479362641487ee9cbf736

**Comment by sngrl** [comment]
Fixed
