### ISSUE TITLE
composer install warning

### ISSUE THREAD

**Issue by dingman** [sngrl/sphinxsearch#30]
I'm getting this warning whenever I add this package. Is there a resolution to address it?

Warning: Ambiguous class resolution, "Sphinx\SphinxClient" was found in both "/home/vagrant/code/vendor/kamikax/wtsphinxphp/src/Sphinx/SphinxClient.php" and "/home/vagrant/code/vendor/gigablah/sphinxphp/src/Sphinx/SphinxClient.php", the first will be used.

**Comment by sngrl** [comment]
Remove previously installed package kamikax/wtsphinxphp

**Comment by dingman** [comment]
thanks!
